config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks" 
  }
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/destroy', to: "users#destroy"

  root to: "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :bigint           not null, primary key
#  current_sign_in_at  :datetime
#  current_sign_in_ip  :string
#  email               :string           default(""), not null, indexed
#  last_sign_in_at     :datetime
#  last_sign_in_ip     :string
#  provider            :string
#  remember_created_at :datetime
#  settings            :jsonb
#  sign_in_count       :integer          default(0), not null
#  uid                 :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :rememberable, :trackable, :omniauthable, :timeoutable, omniauth_providers: %i[spotify]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def new_session_path(scope)
    new_user_session_path
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController  
  def spotify
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user
      auth = request.env["omniauth.auth"]
      spotify_user = RSpotify::User.new(auth).to_hash
      @user.update(settings: spotify_user)
      
      sign_in_and_redirect @user, event: :authentication

      ArchiverWorker.perform_async(@user.id)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  def destroy
    current_user.destroy
    redirect_to root_path, notice: 'Your account was deleted successfully!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotify Archive</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script data-search-pseudo-elements src="https://kit.fontawesome.com/3ebaf2334e.js"></script>
  </head>

  <body class="<%= yield (:body_class) %>">
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% content_for :body_class, "d-flex align-items-center bg-auth border-top border-top-4 border-dark landing" %>

<% if current_user %>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-12 order-xl-1 order-1 my-5">
        <div class="text-center">
          <h1 class="display-4 mb-3">
            You're all set!
          </h1>

          <h5>
            Check your Spotify account for the "My Archive" playlist & wait for weekly updates!
          </h5>

          <p class="text-muted mb-4">
            <img src="https://i.pinimg.com/originals/47/4b/b5/474bb51f05a33360d70f18cbde9fd18c.gif" alt="Ron Swanson Dancing">
          </p>

          <%= link_to "Revoke Access".html_safe, destroy_path, class: 'btn btn-lg btn-danger mb-5 font-weight-bolder', style: 'font-size:1.5em;' %>
        </div>

      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-12 order-xl-1 order-1 my-5">
        <div class="text-center">
          <h1 class="display-4 mb-3">
            Archive Discover Weekly & Release Radar playlists!
          </h1>

          <p class="text-muted mb-4">
            This tool creates a playlist called <i>"My Archive"</i> for you and archives the tracks from Discover Weekly & Release Radar playlists created by Spotify every week, so you don't have to!
          </p>

          <%= link_to "<i class='fab fa-spotify'></i> Sign in with Spotify".html_safe, omniauth_authorize_path('user', 'spotify'), method: :post, class: 'btn btn-lg btn-success mb-5 font-weight-bolder', style: 'font-size:1.5em;' %>
        </div>

      </div>
    </div>
  </div>
<% end %>